export interface Section {
  id: string;
  title: string;
  content: string;
}

export const tutorialData: Section[] = [
  {
    id: "intro",
    title: "🦞 OpenClaw (Mac + 飞书) 排雷教程",
    content: `> **最后更新**：2026 年 3 月 · 适用版本：OpenClaw v2026.3.x\n\n**OpenClaw 是什么？** 一个可以自部署在你电脑上的 AI 助手引擎，能通过飞书/微信等聊天工具远程指挥你的电脑干活（读写文件、搜索资料、执行命令等）。\n\n**两种安装方式**：\n\n| 方式 | 适合谁 | 说明 |\n| --- | --- | --- |\n| **OpenClaw.app**（桌面客户端） | 喜欢图形界面的用户 | 从 openclaw.ai 下载 \`.dmg\` 安装包，双击拖进应用程序文件夹即可。**但它只是个图形壳子，核心仍然依赖 CLI（命令行工具）** |\n| **纯命令行安装** | 所有用户通用 | 本教程的主线路径，一步步在终端里操作 |\n\n> [!IMPORTANT]\n> **不管你选哪种方式，都必须先装好 Homebrew 和 Node.js（步骤 1-2）。** OpenClaw.app 本身也需要 CLI 才能正常工作。\n\n这份教程分为三个阶段。请像跟着菜谱做菜一样，一步步按顺序执行，**绝对不要跳步**！`
  },
  {
    id: "phase-1",
    title: "🟢 第一阶段：给 Mac 装上 OpenClaw（基础环境）",
    content: `> [!WARNING]\n> **已经安装了 OpenClaw.app 的用户请注意！**\n> 如果你双击打开 App 后提示「需要安装 OpenClaw CLI」，点击安装按钮后**窗口闪一下就消失了**——这是一个已知问题。原因是你的 Mac 上还没有装 Node.js，App 尝试执行 \`npm install\` 但瞬间失败了。\n>\n> **解决办法很简单**：别管 App 里的按钮，跟着下面步骤 1、2、3 手动在终端装好环境和 CLI，回来再打开 App 就正常了。\n\n### 步骤 1：安装 Homebrew（Mac 的「应用商店」命令行版）\n\n> 如果你已经装过 Homebrew，可以跳到步骤 2。\n\n1. **做什么**：按住键盘上的 \`Command ⌘\` + 空格键，搜索并**打开 \`终端\` (Terminal)**。在黑框里复制粘贴下面这行代码并回车：\n   \`\`\`bash\n   /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"\n   \`\`\`\n2. **预期看到什么**：终端会下载安装 Homebrew，过程中可能要求你输入 **Mac 开机密码**（输入时屏幕不显示字符，正常现象，输完按回车）。最后看到 \`==> Installation successful!\` 表示成功。\n3. **出错了怎么办？**\n   - **下载超级慢或者卡住**：网络问题。换个梯子或者使用国内镜像源：\n     \`\`\`bash\n     /bin/bash -c "$(curl -fsSL https://gitee.com/ineo6/homebrew-install/raw/master/install.sh)"\n     \`\`\`\n   - **Apple Silicon Mac (M1/M2/M3/M4) 安装后提示找不到 \`brew\` 命令**：需要手动添加环境变量，把下面两行复制粘贴进终端：\n     \`\`\`bash\n     echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> ~/.zprofile\n     eval "$(/opt/homebrew/bin/brew shellenv)"\n     \`\`\`\n\n### 步骤 2：安装 Node.js（OpenClaw 的运行引擎）\n\n1. **做什么**：在终端输入并回车：\n   \`\`\`bash\n   brew install node\n   \`\`\`\n2. **验证安装**：安装完后输入：\n   \`\`\`bash\n   node --version\n   \`\`\`\n3. **预期看到什么**：屏幕上应该显示类似 \`v22.0.0\` 或更高的版本号。**必须 ≥ v22，否则后面会报错！**\n4. **出错了怎么办？**\n   - **版本低于 22**：\n     \`\`\`bash\n     brew upgrade node\n     \`\`\`\n   - **不想用 Homebrew / 上面的方法不管用**：直接去 Node.js 官网 下载最新 Mac 安装包 (.pkg)，双击安装。装完后**关掉终端重新打开**，再输入 \`node --version\` 检查。\n\n> [!NOTE]\n> 同时验证一下对应的包管理器 npm 是否正常：输入 \`npm --version\`，结果应显示 \`10.x.x\` 或更高。\n\n### 步骤 3：一键安装 OpenClaw CLI（命令行核心）\n\n> [!NOTE]\n> **如果你已经安装了 OpenClaw.app**：这一步就是帮 App 补上它缺少的 CLI。装完之后重新打开 App，它就不会再提示「需要安装 CLI」了。\n\n1. **做什么**：在终端里复制粘贴下面这行代码，按回车：\n   \`\`\`bash\n   curl -fsSL https://openclaw.ai/install.sh | bash\n   \`\`\`\n2. **预期看到什么**：屏幕会像黑客帝国一样疯狂滚动代码，最后提示安装成功。整个过程大概 2-5 分钟。\n3. **出错了怎么办？**\n\n| 报错关键词 | 原因 | 解决办法 |\n| --- | --- | --- |\n| \`Permission Denied\` | 权限不足 | 换用：\`sudo npm install -g openclaw@latest\`（输入开机密码，不显示字符是正常的） |\n| \`libvips\` 或 \`sharp\` | Mac 图像处理组件卡壳 | 换用：\`SHARP_IGNORE_GLOBAL_LIBVIPS=1 npm install -g openclaw@latest\` |\n| \`EACCES\` | npm 全局目录权限问题 | 先执行 \`sudo chown -R $(whoami) $(npm config get prefix)/{lib/node_modules,bin,share}\` 再重试安装 |\n| \`network\` / \`timeout\` | 网络超时 | 使用国内镜像：\`npm install -g openclaw@latest --registry=https://registry.npmmirror.com\` |\n\n### 步骤 4：验证是否安装成功\n\n1. **做什么**：在终端输入：\n   \`\`\`bash\n   openclaw --version\n   \`\`\`\n2. **预期看到什么**：屏幕打印出版本号，比如 \`2026.3.8\`。\n3. **出错了怎么办？**\n   - **报错 \`command not found: openclaw\`**：说明电脑"找不到"刚装好的软件。\n   - **解决办法**：输入这行代码把路径加进去：\n     \`\`\`bash\n     echo 'export PATH="$(npm prefix -g)/bin:$PATH"' >> ~/.zshrc\n     source ~/.zshrc\n     \`\`\`\n     然后再试一次。如果还不行，**关掉终端重新打开**再试。`
  },
  {
    id: "phase-2",
    title: "🟡 第二阶段：🚨 破解最新版的封印（核心避坑）",
    content: `> [!CAUTION]\n> **新手必看**：OpenClaw 最近加了严格的安全锁。如果不做下面这几步，你的 AI 根本启动不了，或者只是个"只会聊天不能帮你干活"的废物！\n\n### 步骤 5：运行初始化向导（必须第一个做！）\n\n> [!IMPORTANT]\n> **为什么要先做这一步？** \`openclaw onboard\` 是初始化向导，会帮你配置 AI 模型、API Key 和基础网关设置。如果你先手动改了配置再跑向导，**向导可能会覆盖你的设置**，导致白忙一场。所以一定要先跑向导，再做后面的精细调整。\n\n1. **做什么**：在终端输入：\n   \`\`\`bash\n   openclaw onboard --install-daemon\n   \`\`\`\n2. **预期看到什么**：屏幕上会出现类似问卷调查的选择题。\n   - 用键盘**上下键**选择 \`QuickStart\`（快速启动），按回车。\n   - 选择大模型。\n   - 选择工作目录。为了安全考虑，推荐创建一个**单独的目录**用于 OpenClaw 工作。\n   - 根据提示粘贴你申请的 API Key（去大模型官网免费申请）。\n   - 聊天平台这一步选 \`None\`（我们下面单独搞飞书）。\n   - 一路回车到底，最后它会帮你重启 Gateway 网关。\n3. **确认网关已启动 + 开机自启**：\n   - \`--install-daemon\` 参数已经帮你做了两件事：① 启动网关服务；② 注册为 macOS 开机自启服务。\n   - 验证网关是否在跑：\n     \`\`\`bash\n     openclaw gateway status\n     \`\`\`\n     应该看到状态为 \`running\`。如果没启动，手动拉起：\n     \`\`\`bash\n     openclaw gateway start\n     \`\`\`\n   - 如果开机自启没生效，可以手动补装：\n     \`\`\`bash\n     openclaw daemon install\n     \`\`\`\n4. **出错了怎么办？**\n   - **提示 \`Invalid API key\` / \`Authentication failed\`**：API Key 粘贴错了或者已过期。回到大模型官网重新生成一个。\n   - **提示端口冲突 (\`port already in use\`)**：另一个程序占了 18789 端口。换端口：\n     \`\`\`bash\n     openclaw config set gateway.port 18790\n     \`\`\`\n\n### 步骤 6：解开网关认证锁（v2026.3.7+ 必做）\n\n1. **做什么**：新版强行要求必须设密码，禁止裸奔。依次在终端执行这两行命令（把 \`YourStrongPassword123!\` 换成你自己编的**强密码**）：\n   \`\`\`bash\n   openclaw config set gateway.auth.mode token\n   openclaw config set gateway.auth.token "YourStrongPassword123!"\n   \`\`\`\n2. **预期看到什么**：终端没有任何红字报错，安静地跳到下一行。\n\n> [!IMPORTANT]\n> **安全提示**：这个 token 就是你的"管理员密码"，请使用复杂密码并妥善保管。不要用 \`123456\` 这种弱密码！建议定期更换。密码保存在 \`~/.openclaw/openclaw.json\` 中。\n\n### 步骤 7：解开"干活"能力锁（v2026.3.2+ 必做）\n\n> [!WARNING]\n> **这一步是必须的！** 从 v2026.3.2 起，OpenClaw 默认把 AI 限制在 \`messaging\`（纯聊天）模式，**无法读写文件、无法执行命令、无法上网搜索**。如果你希望 AI 能帮你干活（而不是只聊天），就必须手动切换。在 Windows 上也是同样的操作，只是有时向导会自动帮你设置所以可能没注意到。\n\n1. **做什么**：\n   \`\`\`bash\n   openclaw config set tools.profile full\n   \`\`\`\n2. **预期看到什么**：安静地跳到下一行。\n3. **重启网关使配置生效**：\n   \`\`\`bash\n   openclaw gateway restart\n   \`\`\`\n4. **安全检查**（可选）：开了 \`full\` 模式后，建议跑一次安全审计确认没有过度暴露：\n   \`\`\`bash\n   openclaw security audit\n   \`\`\`\n   如果有风险项，它会告诉你怎么收紧权限。\n\n### 步骤 8：跑一次全面体检 🩺\n\n> 这一步不是必须的，但**强烈推荐**！它能帮你自动检测并修复常见问题。\n\n\`\`\`bash\nopenclaw doctor\n\`\`\`\n**预期看到什么**：像医生诊断一样，逐项检查你的配置，通过的显示 ✅，有问题的显示 ❌ 并给出修复建议。\n\n**其他有用的诊断命令**（出问题时随时用）：\n\n| 命令 | 作用 |\n| --- | --- |\n| \`openclaw status\` | 快速查看各渠道连接状态 |\n| \`openclaw status --all\` | 输出详细诊断报告 |\n| \`openclaw health --verbose\` | 显示网关地址、配置路径等详细信息 |\n| \`openclaw logs --follow\` | 实时查看日志（像监控摄像头一样滚动） |\n| \`openclaw gateway status\` | 查看网关是否在运行 |\n| \`openclaw gateway probe\` | 检测网关是否可达 |\n| \`openclaw models list --all\` | 查看当前已配置的所有 AI 模型 |\n| \`openclaw security audit\` | 安全审计，检查工具权限是否过度暴露 |`
  },
  {
    id: "phase-3",
    title: "🔴 第三阶段：接入飞书（让 AI 进驻你的手机）",
    content: `### 步骤 9：去飞书领一个机器人的"身份证"\n\n1. **做什么**：电脑浏览器打开 飞书开放平台，用你的飞书扫码登录。\n2. 点击 **"创建企业自建应用"**，随便起个名字（比如：贾维斯）。\n3. 点击左侧菜单的 **"凭证与基础信息"**。\n4. **预期看到什么**：你会看到 **App ID** (类似 \`cli_xxxxx\`) 和一长串的 **App Secret**。\n   - **重点**：新建一个记事本，把这俩复制进去，千万别关掉网页，等下马上要用！\n\n> [!WARNING]\n> **App Secret 是机密信息**，相当于你机器人的密码。不要截图发到群里，不要提交到 GitHub！\n\n### 步骤 10：给机器人赋予"灵魂"（极其容易出错的一步！）\n\n1. **做什么**：\n   - 在刚才的飞书网页，点击左侧 **"应用能力" → "机器人"**，**打开启用开关**。\n   - 点击左侧 **"权限管理"**，在搜索框里**精确搜索**并勾选以下权限：\n\n| # | 权限名称 | 权限 ID | 备注 |\n| --- | --- | --- | --- |\n| 1 | 获取与发送单聊、群组消息 | \`im:message\` | 基础收发消息 |\n| 2 | 以应用身份发消息 | \`im:message:send_as_bot\` | 让机器人能主动发消息 |\n| 3 | 获取通讯录基本信息 | \`contact:contact.base:readonly\` | ⚠️ **漏了这个，机器人不认识你，死活不回消息！** |\n| 4 | 获取群组基本信息（可选） | \`im:chat:readonly\` | 如果要把机器人拉进群聊就需要 |\n\n2. **预期看到什么**：权限列表里这些已成功添加。\n\n### 步骤 11：打开接收消息的"长连接天线" 📡\n\n1. **做什么**：\n   - 点击左侧 **"事件订阅"**。\n   - 勾选 **"使用长连接接收事件"** (WebSocket 模式)。\n   > [!TIP]\n   > 用 WebSocket 长连接的好处是**不需要公网服务器、不用配域名**，在家就能跑。\n   - 在下方的"添加事件"里，搜索并添加以下事件：\n\n| 事件 | 事件 ID | 备注 |\n| --- | --- | --- |\n| 接收消息 | \`im.message.receive_v1\` | **必加**，是机器人收消息的唯一通道 |\n| 消息已读 (可选) | \`im.message.message_read_v1\` | 让机器人知道你读了它的消息 |\n| 机器人进群 (可选) | \`im.chat.member.bot.added_v1\` | 群聊场景需要 |\n\n   - 最后！点击左侧最下面的 **"版本管理与发布"**，点击 **"创建版本"** 并 **"发布"**。\n\n2. **预期看到什么**：应用状态显示为 **"已上架"** 或 **"已发布"**。\n\n### 步骤 12：在 Mac 上绑定飞书并启动\n\n1. **做什么**：回到 Mac 终端，输入：\n   \`\`\`bash\n   openclaw channels add\n   \`\`\`\n2. **预期看到什么**：屏幕问你选哪个渠道。用上下键选 \`Feishu\`。然后把你在步骤 9 记事本里存的 **App ID** 和 **App Secret** 粘贴进去。\n3. **完成绑定后，重启服务使之生效**：\n   \`\`\`bash\n   openclaw gateway restart\n   \`\`\`\n4. **验证渠道状态**：\n   \`\`\`bash\n   openclaw channels status --probe\n   \`\`\`\n   应该看到 Feishu 渠道状态为 \`connected\` 或 ✅。\n\n### 步骤 13：在手机上"认主配对"\n\n1. **做什么**：打开手机飞书 APP，在最上面的搜索框搜你刚才起的名字（比如"贾维斯"），点进去发一句："\`你好\`"。\n2. **预期看到什么**：它会秒回你一串 **【配对码】**（比如：\`ABC1234\`）。这说明你的服务器和飞书已经通了！\n3. **出错了怎么办？**\n   **情况 A：发了消息，石沉大海不回**\n   - 先在终端查日志：\`openclaw logs --follow\`\n   - 日志没反应 → **步骤 11 的事件订阅/长连接没配对**，或者**应用没发布**。回飞书后台检查并重新发布。\n   - 日志有红字报错 → 大概率是**步骤 10 的权限漏了**（尤其是 \`contact:contact.base:readonly\`），回去补上并重新发布。\n\n   **情况 B：飞书搜不到机器人**\n   - 你的飞书应用还没发布，或发布后还没生效（等几分钟再搜）。\n   - 确认你搜索时登录的飞书账号和创建应用的是**同一个企业/组织**。\n\n### 步骤 14：批准配对，彻底解锁！\n\n1. **做什么**：回到 Mac 终端，敲入这行最终指令（把 \`ABC1234\` 换成你手机收到的码）：\n   \`\`\`bash\n   openclaw pairing approve feishu ABC1234\n   \`\`\`\n2. **预期看到什么**：终端显示批准成功。`
  },
  {
    id: "success",
    title: "🎉 大功告成！",
    content: `去飞书里对它说：**"帮我搜索一下电脑里名字带'发票'的文件"** 试试吧！你的专属超级个体引擎已点火完毕！🚀`
  },
  {
    id: "advanced-1",
    title: "🖥️ 进阶：OpenClaw.app 桌面客户端使用指南",
    content: `> 前面所有步骤都是在终端里完成的。如果你还安装了 **OpenClaw.app**（桌面客户端），现在可以打开它来解锁更多能力。**CLI 是引擎，App 是仪表盘**——没有 App 也能用，但有了 App 会更方便。\n\n### App 能做什么？\n\n| 功能 | 说明 |\n| --- | --- |\n| 📊 **菜单栏管理中心** | Mac 右上角常驻图标，一眼看到网关状态，可快速启动/停止/重启网关 |\n| 💬 **内置聊天界面** | 自带 WebChat，不用开浏览器就能直接和 AI 对话 |\n| 🔐 **macOS 权限管理** | 帮你处理 macOS 的权限弹窗（通知、辅助功能、屏幕录制、麦克风等） |\n| 🍎 **Mac 专属能力** | 向 AI 暴露 Mac 独有工具：截屏/录屏、摄像头、AppleScript 自动化 |\n| 🎤 **语音交互** | 支持按键说话 (Push-to-Talk)，用语音和 AI 对话 |\n| 🌐 **远程网关管理** | 可通过 SSH 连接并控制其他机器上的 OpenClaw Gateway |\n\n### 如何使用？\n\n1. **打开 App**：双击 OpenClaw.app（如果之前按教程装好了 CLI，App 会自动检测到，不会再闪退）。\n2. **菜单栏图标**：App 启动后会在 Mac 右上角菜单栏出现一个小图标。点击它可以：\n   - 查看网关运行状态\n   - 快速重启网关\n   - 打开内置聊天窗口\n3. **授权系统权限**：App 可能会弹出 macOS 权限请求弹窗（如"是否允许屏幕录制"），根据需要选择允许。这些权限让 AI 能使用截屏、操控窗口等高级功能。\n4. **后台运行**：即使关掉 App 窗口，网关服务仍在后台通过 \`launchd\` 静默运行，不影响飞书机器人的正常使用。\n\n> [!TIP]\n> **什么时候需要 App？**\n> - ✅ 想用语音和 AI 交互 → **需要 App**\n> - ✅ 想让 AI 截屏/录屏/操控窗口 → **需要 App**（macOS 权限必须通过 App 授权）\n> - ✅ 不想开终端，想用图形界面管理网关 → **需要 App**\n> - ❌ 只用飞书和 AI 聊天、操作文件 → **不需要 App**，纯 CLI 就够了`
  },
  {
    id: "advanced-2",
    title: "🔒 高阶：安全配置实操指南（Mac 篇）",
    content: `> 这是一份进阶教程，帮你配置**终端命令的白名单与强制确认机制**，防止 AI 执行危险操作。适合对安全有较高要求的用户。\n\n### 终端命令的"白名单与强制确认"\n\n在新版 OpenClaw (2026.3.8+) 中，旧版的 \`denyCommands\` 黑名单已被废弃，改为更安全的**白名单 + 逐条审批**机制。\n\n#### 1. 声明安全策略\n\n打开 OpenClaw 配置文件：\n\`\`\`bash\nopen ~/.openclaw/openclaw.json\n\`\`\`\n找到 \`agents.list.main.tools.exec\` 配置块（如果没有就手动添加），修改为白名单模式并开启强制询问：\n\`\`\`json\n"tools": {\n  "exec": {\n    "security": "allowlist",\n    "ask": "always"\n  }\n}\n\`\`\`\n\n| 参数 | 可选值 | 说明 |\n| --- | --- | --- |\n| \`security\` | \`"deny"\` / \`"allowlist"\` / \`"full"\` | \`allowlist\` = 只允许白名单内的命令 |\n| \`ask\` | \`"always"\` / \`"on-miss"\` / \`"off"\` | \`always\` = 每次执行都要你确认；\`on-miss\` = 白名单外才问 |\n| \`askFallback\` | \`"deny"\` / \`"allow"\` | 当 App 不在前台无法弹窗时的默认行为，建议 \`"deny"\` |\n\n#### 2. 定义命令白名单\n\n打开或创建 \`~/.openclaw/exec-approvals.json\`：\n\`\`\`bash\nopen ~/.openclaw/exec-approvals.json\n\`\`\`\n\n> [!IMPORTANT]\n> 文件中的 \`socket.path\` 和 \`socket.token\` 是你本机自动生成的凭证，**不要修改它们**。只需在 \`agents.main\` 下配置白名单即可。\n\n以下是适配 Mac 的命令白名单示例（已去掉 Windows 专属命令，换成 Mac/Unix 命令）：\n\`\`\`json\n{\n  "version": 1,\n  "socket": {\n    "path": "/Users/你的用户名/.openclaw/exec-approvals.sock",\n    "token": "你的本机自动生成的token不要改"\n  },\n  "defaults": {\n    "security": "deny",\n    "ask": "always",\n    "askFallback": "deny"\n  },\n  "agents": {\n    "main": {\n      "security": "allowlist",\n      "ask": "always",\n      "allowlist": [\n        { "pattern": "python*" },\n        { "pattern": "python3*" },\n        { "pattern": "openclaw*" },\n        { "pattern": "git*" },\n        { "pattern": "npm*" },\n        { "pattern": "node*" },\n        { "pattern": "pip*" },\n        { "pattern": "pip3*" },\n        { "pattern": "brew*" },\n        { "pattern": "curl*" },\n        { "pattern": "trash*" },\n        { "pattern": "ls*" },\n        { "pattern": "cat*" },\n        { "pattern": "head*" },\n        { "pattern": "tail*" },\n        { "pattern": "grep*" },\n        { "pattern": "find*" },\n        { "pattern": "wc*" },\n        { "pattern": "mkdir*" },\n        { "pattern": "echo*" },\n        { "pattern": "cd*" },\n        { "pattern": "cp*" },\n        { "pattern": "mv*" },\n        { "pattern": "open*" },\n        { "pattern": "which*" },\n        { "pattern": "whoami*" }\n      ]\n    }\n  }\n}\n\`\`\`\n\n> [!CAUTION]\n> **Windows → Mac 命令对照表**（已在上面的白名单中适配）：\n> \n> | Windows | Mac/Unix | 说明 |\n> | --- | --- | --- |\n> | \`dir\` | \`ls\` | 列出文件 |\n> | \`type\` | \`cat\` | 查看文件内容 |\n> | \`copy\` | \`cp\` | 复制文件 |\n> | \`move\` | \`mv\` | 移动/重命名文件 |\n> | \`del\` / \`rm\` | \`trash\` | 删除文件（用 trash 更安全） |\n> | — | \`open\` | Mac 独有，用默认程序打开文件 |\n> | — | \`which\` | 查看命令所在路径 |\n> | — | \`brew\` | Mac 独有的包管理器 |\n\n修改完后重启网关使配置生效：\n\`\`\`bash\nopenclaw gateway restart\n\`\`\``
  },
  {
    id: "faq",
    title: "🧰 附录：常见问题 FAQ",
    content: `**Q: 如何升级 OpenClaw？**\n\`\`\`bash\nsudo npm install -g openclaw@latest\nopenclaw gateway restart\n\`\`\`\n升级后建议跑一次 \`openclaw doctor\` 检查。\n\n**Q: 如何更换 AI 大模型 / 添加新的 API Key？**\n有三种方法，任选其一：\n\n**方法 1：重新跑向导（推荐，最简单）**\n\`\`\`bash\nopenclaw onboard\n\`\`\`\n向导会检测到你已有配置，提示你选择 \`Update existing value\`（更新现有值），然后重新选择模型和 API Key。跟 Windows 上的操作一模一样。\n\n**方法 2：CLI 命令行直接换**\n\`\`\`bash\n# 先看看当前有哪些模型\nopenclaw models list --all\n\n# 切换默认模型\nopenclaw models set <模型名称>\n\n# 重启网关生效\nopenclaw gateway restart\n\`\`\`\n\n**方法 3：直接编辑配置文件（高级用户）**\n\`\`\`bash\nopen ~/.openclaw/openclaw.json\n\`\`\`\n修改完后记得 \`openclaw gateway restart\` 重启网关。\n\n**Q: 想让 Mac 开机自动启动 OpenClaw 怎么办？**\n在步骤 7 使用了 \`--install-daemon\` 参数后，OpenClaw 会注册为系统服务，开机自动启动。如果你跳过了这一步：\n\`\`\`bash\nopenclaw daemon install\n\`\`\`\n\n**Q: 配置文件在哪？日志在哪？**\n\n| 文件 | 路径 |\n| --- | --- |\n| 配置文件 | \`~/.openclaw/openclaw.json\` |\n| 日志文件 | \`~/.openclaw/gateway.log\` |\n| PID 文件 | \`~/.openclaw/gateway.pid\` |\n| 渠道凭证 | \`~/.openclaw/agents/<agentId>/agent/auth-profiles.json\` |\n\n**Q: Gateway 崩溃了/起不来怎么排查？**\n1. 先看日志：\`openclaw logs --follow\`\n2. 运行诊断：\`openclaw doctor\`\n3. 检查端口占用：\`lsof -i :18789\`\n4. 如果有残留进程挡路，删除 PID 文件并重启：\n   \`\`\`bash\n   rm ~/.openclaw/gateway.pid\n   openclaw gateway restart\n   \`\`\`\n5. 如果是插件问题（日志中出现 \`WebSocket 1006\`），临时禁用非核心插件排查。\n\n**Q: 网关默认端口 18789 被占了怎么办？**\n\`\`\`bash\nopenclaw config set gateway.port 18790\nopenclaw gateway restart\n\`\`\``
  }
];
